services:
  # ==========================
  # Frontend container
  # ==========================
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    container_name: wellness-frontend-container
    ports:
      - "8080:80"                 # Host 8080 â†’ contenedor 80
    networks:
      - web_net
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://localhost"]
      interval: 10s
      timeout: 3s
      retries: 3

  # ==========================
  # Nginx Reverse Proxy
  # ==========================
  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile.dev
    container_name: wellness-nginx-proxy
    ports:
      - "80:80"                   # Punto de entrada al sistema
    depends_on:
      - frontend
      - backend
    networks:
      - web_net
      - backend_net
    volumes:
    - ./nginx/nginx.dev.conf:/etc/nginx/conf.d/default.conf:ro  
    restart: unless-stopped

  # ==========================
  # Backend API
  # ==========================
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    container_name: wellness-backend-container
    env_file:
      - env/dev/.env
    depends_on:
      - postgres  
    networks:
      - backend_net               # Red separada (seguridad)
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://localhost:3000/health"]
      interval: 10s
      timeout: 3s
      retries: 3

  # ==========================
  # PostgreSQL Database
  # ==========================
  postgres:
    image: postgres:15-alpine
    container_name: wellness-postgres-db
    env_file:
      - env/dev/.env
    volumes:
      - db-data:/var/lib/postgresql/data   # Persistencia real
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    networks:
      - backend_net
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U wellness"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

 # ==========================
  # prometheus
  # ==========================

  prometheus:
    image: prom/prometheus:latest
    container_name: wellness-prometheus
    volumes:
      - ./monitoring/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
    ports:
      - "9090:9090"
    depends_on:
      - backend
    networks:
      - backend_net
# ==========================
  # grafana
  # ==========================

  grafana:
    image: grafana/grafana:latest
    container_name: wellness-grafana
    ports:
    - "3001:3000"
    depends_on:
    - prometheus
    networks:
    - backend_net

# ==========================
# Networks
# ==========================
networks:
  web_net:
    driver: bridge

  backend_net:
    driver: bridge

# ==========================
# Volumes
# ==========================


volumes:
  db-data:
