apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-gateway-config
data:
  nginx.conf: |
    events {}

    http {
      upstream backend_upstream {
        server backend:3000;
      }

      upstream frontend_upstream {
        server frontend-service:80;
      }

      server {
        listen 80;

        location /api/ {
          proxy_pass http://backend_upstream;
          proxy_set_header Host $host;
          proxy_set_header X-Real-IP $remote_addr;
          proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        }

        location / {
          proxy_pass http://frontend_upstream/;
          proxy_set_header Host $host;
          proxy_set_header X-Real-IP $remote_addr;
          proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        }
      }
    }
