apiVersion: v1
data:
  DB_HOST: postgres-service
  DB_NAME: wellness
  DB_PORT: "5432"
  NODE_ENV: production
  PORT: "3000"
kind: ConfigMap
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","data":{"DB_HOST":"postgres-service","DB_NAME":"wellness","DB_PORT":"5432","NODE_ENV":"production","PORT":"3000"},"kind":"ConfigMap","metadata":{"annotations":{},"name":"backend-config","namespace":"default"}}
  creationTimestamp: "2026-02-13T16:03:45Z"
  name: backend-config
  namespace: canary-lab
  resourceVersion: "4174"
  uid: 28d221c3-d3a7-4ca3-b572-b13ce26714f4
