apiVersion: v1
data:
  DB_PASSWORD: d2VsbG5lc3M=
  DB_USER: cG9zdGdyZXM=
  POSTGRES_DB: d2VsbG5lc3M=
  POSTGRES_PASSWORD: d2VsbG5lc3M=
  POSTGRES_USER: cG9zdGdyZXM=
kind: Secret
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"Secret","metadata":{"annotations":{},"name":"backend-secret","namespace":"default"},"stringData":{"POSTGRES_DB":"wellness","POSTGRES_PASSWORD":"wellness","POSTGRES_USER":"postgres"},"type":"Opaque"}
  creationTimestamp: "2026-02-13T16:03:45Z"
  name: backend-secret
  namespace: canary-lab
  resourceVersion: "87236"
  uid: 8d618d66-59f9-44df-b585-8849941de639
type: Opaque
