apiVersion: v1
data:
  JWT_SECRET: c3VwZXJzZWNyZXRrZXktY2hhbmdlLW1l
kind: Secret
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","data":{"JWT_SECRET":"c3VwZXJzZWNyZXRrZXktY2hhbmdlLW1l"},"kind":"Secret","metadata":{"annotations":{},"name":"backend-jwt-secret","namespace":"default"}}
  creationTimestamp: "2026-02-13T16:03:45Z"
  name: backend-jwt-secret
  namespace: canary-lab
  resourceVersion: "4177"
  uid: fc911f48-d564-41be-8c6a-c5cd144b4106
type: Opaque
