apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: wellness-ca
  namespace: cert-manager
spec:
  isCA: true
  commonName: wellness-ca
  secretName: wellness-ca-secret
  duration: 87600h # 10 a√±os
  issuerRef:
    name: selfsigned-issuer
    kind: ClusterIssuer
