apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: wellness-tls
  namespace: default
spec:
  secretName: wellness-tls
  duration: 2160h # 90 días
  renewBefore: 360h # 15 días
  issuerRef:
    name: wellness-ca
    kind: ClusterIssuer
  commonName: wellness.127.0.0.1.nip.io
  dnsNames:
    - wellness.127.0.0.1.nip.io
