name: Runner Proof FINALv2

on:
    workflow_dispatch:

jobs:
    proof:
        runs-on: [self-hosted, Linux, X64]

        steps:
            - name: Proof
              run: |
                  echo "RUNNER OK"
                  echo "Repo: $GITHUB_REPOSITORY"
                  hostname
                  whoami
                  pwd
