name: Runner Proof FINAL

on:
    workflow_dispatch:

jobs:
    proof:
        runs-on: [self-hosted, Linux, X64]

        steps:
            - name: Proof execution
              run: |
                  echo "RUNNING ON SELF-HOSTED RUNNER"
                  hostname
                  whoami
                  pwd
                  date
